### ISSUE TITLE
dev-* links are broken

### ISSUE THREAD

**Issue by amyipdev** [acmcsufoss/acmcsuf.com#1019]
### What happened?

All `dev-*` links redirect to a broken Discord link.

**Comment by EthanThatOneKid** [comment]
> All `dev-*` links redirect to a broken Discord link.

Can you please provide a specific example? I am having trouble reproducing the error.

**Comment by amyipdev** [comment]
https://acmcsuf.com/dev-intro
https://acmcsuf.com/dev-hfhsjfjsbdjfhd

These both redirect to:

https://discord.com/invite/eKRApG627bev-{whatever is after the dev}

Such as 

https://discord.com/invite/eKRApG627bev-hfhsjfjsbdjfhd
