### ISSUE TITLE
`npm run all` checks imply failure (status code 1) for non-env-holding users

### ISSUE THREAD

**Issue by amyipdev** [acmcsufoss/acmcsuf.com#1020]
### What happened?

When running `npm run all`, `svelte-check` yields 5 errors due to not having specific environment-variable secrets. While this is reasonable when running on-server, for development, this is unnecessary, and may confuse newer developers. 

Recommendation: "soft fail" on environment variable-related `svelte-check` arguments.

**Comment by amyipdev** [comment]
Note: I am aware that the contributor's guide recommends users set up their .env, however my point still stands that these should be warnings, not hard failures. GCAL_API_KEY also fails and is not mentioned in the contributor guide.

**Comment by EthanThatOneKid** [comment]
> and may confuse newer developers

I agree with the sentiment of this issue. Thanks for reporting 👍

**Comment by EthanThatOneKid** [comment]
While this is a limitation of SvelteKit's environment variable handling, there's a workaround. SvelteKit restricts environment variables to client-side, server-side, or both for security reasons.

As a temporary solution, you can copy all necessary variables from `.env.example` to `.env`. Just use empty strings (`""`) as placeholders for the missing values.

For more details on SvelteKit's environment variables, refer to the documentation: [https://learn.svelte.dev/tutorial/env-dynamic-private](https://learn.svelte.dev/tutorial/env-dynamic-private).

**Comment by amyipdev** [comment]
What about adding a note to the README about that?

**Comment by EthanThatOneKid** [comment]
> What about adding a note to the README about that?

The current instructions for setting up the `.env` file are in our [`CONTRIBUTING.md`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/68ea555559bf04a41608852dbf2e82729500ca8b/CONTRIBUTING.md?plain=1#L101) document. However, it's been a while since we've updated that section. Do you think it might need to be clearer or more detailed?

**Comment by amyipdev** [comment]
Definitely, it needs to be updated - it does not meet the current requirements.
