### ISSUE TITLE
Flickery light moving between pages in dark mode

### ISSUE THREAD

**Issue by tomasohCHOM** [acmcsufoss/acmcsuf.com#1034]
## Video showcasing the bug (using Chrome Browser)
https://github.com/EthanThatOneKid/acmcsuf.com/assets/112128328/87e15fdb-8ca9-4049-a854-6098c8de8931

Moving between pages in dark mode will make light mode appear for a quick second, then transitions to dark mode again. It should just stay in dark whenever we change between pages.

**Comment by k4rni** [comment]
![color](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/c9e3d235-fd3d-4c58-9dbf-2b176fbe29f9)

Another issue I noticed was that the background chose a different color. Thank you for sharing this issue @tomasohCHOM.
