### ISSUE TITLE
Old dev logo on acmcsuf.com/teams page overflows on mobile

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#1057]
### What happened?

Some simple fixes can include:
- Adding logos with less space
- Changing the animation

![dev](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/5caf881d-844a-41ab-b071-a6fa51abef5c)

**Comment by JustinStitt** [comment]
Hi, yeah I guess it technically overflows. The bounding box is pretty big because of the subtle gradient.

Is this overflow actually a problem (i.e: do the users or the developers care)?

**Comment by EthanThatOneKid** [comment]
> Is this overflow actually a problem (i.e: do the users or the developers care)?

It’s generally bad practice to let an element on the page scroll horizontally unintentionally. It can also confuse users.
