### ISSUE TITLE
Socials appear on only first occurence of officer

### ISSUE THREAD

**Issue by EvanCPSC** [acmcsufoss/acmcsuf.com#1064]
## Any other occurence of that officer afterwards, will not pop up the socials at that spot.

i.e. Patrick

![ss1](https://github.com/EthanThatOneKid/acmcsuf.com/assets/142952307/f7e52d60-a49b-4162-a0ae-691d4cf5c597)
![ss2](https://github.com/EthanThatOneKid/acmcsuf.com/assets/142952307/92ae2dcb-0844-4e17-b357-f9c4ec7a51fe)

**Comment by EvanCPSC** [comment]
Found by @AlexthePear and @adriancancode

**Comment by k4rni** [comment]
Fixed in #1067.
