### ISSUE TITLE
Add Portfolio Gallery

### ISSUE THREAD

**Issue by NateGries1** [acmcsufoss/acmcsuf.com#1077]
### What's your idea?

After the portfolio website competition, make a site off of acmcsuf.com for a gallery of all the participants' portfolios to be accessed and visited from.

**Comment by adriancancode** [comment]
Can I start the main structure of this?

**Comment by adriancancode** [comment]
Created the main files for this.  Now i just need to extract the json data for each portfolio and display each website.

**Comment by adriancancode** [comment]
Got the data from the json file loaded onto the page.  Now just need to style it to my liking
