### ISSUE TITLE
Refactor Quiz Page

### ISSUE THREAD

**Issue by 26samaahmed** [acmcsufoss/acmcsuf.com#1083]
### Overview:
- Make the page more maintainable so that we are able to fix issues we're familiar with.
- #1082 
- #1081

**Comment by amyipdev** [comment]
@26samaahmed would you like additional assistance with this?

**Comment by 26samaahmed** [comment]
@amyipdev Yes I would appreciate that a lot. Currently, I believe we can try to identify the problem on the existing code for the quiz page. After I redesigned the page and add the new teams/ modified the questions to be accurate, we've had a problem where if you click on a certain team's grid once u get the result, it redirects to an empty page instead of how it was originally where it give more info about the team. Would you like to work on #1082 ? The issue also include the video of what the problem looks like.

**Comment by 26samaahmed** [comment]
Closed since the issues with the page have been resolved.
