### ISSUE TITLE
Link to OSS gallery

### ISSUE THREAD

**Issue by adriancancode** [acmcsufoss/acmcsuf.com#1089]
### What's your idea?

Now that the gallery that I created is up and running, we need to somehow make a link to it so people could see how much fun we have in OSS :smile: We should also probably make separate galleries for each team and their workshops, maybe even create a dropdown for each semester, kinda like how the teams page has a dropdown for eash semester and who was part of each team in that semester.

**Comment by 26samaahmed** [comment]
Every team will have their own page with their pictures on the new project 'Gallery'. I'll close this for now and we can open it as a new issue in the new repo.
