### ISSUE TITLE
Blog: Syntax highlighting is broken

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#1092]
### What happened?

Blog post syntax highlighting is not working! 😢 
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/31261035/1f2d11ef-3013-4b72-9eaa-018417784723)

**Comment by tmbkoren** [comment]
Did it EVER work? The last commit to this module was made 2 years ago. I've identified that it's not working because css variables in blog/[id]/syntax-highlight.css are not working. when I set the color by hand without variables, it worked.
