### ISSUE TITLE
100 Days of Design Gallery Page

### ISSUE THREAD

**Issue by 26samaahmed** [acmcsufoss/acmcsuf.com#1098]
### What's your idea?

Since a lot of our ACM members have been working hard making the daily design challenges hosted by the Design Team, I want to show case all the amazing designs for people to easily look back on a gallery page!

**Comment by adriancancode** [comment]
Maybe make a gallery of all 100 days, and a gallery within each separate day, basically a slug

**Comment by adriancancode** [comment]
@26samaahmed Want me to start the main gallery and then you can do the slug for the 100 days?

**Comment by 26samaahmed** [comment]
My original thought was to have a drop down menu similar to how you choose terms in acmcsuf.com/teams instead of having all designs on one page. I would have people's discord usernames below each of their designs. I wanted to start the main page first with the day 1 and then you can help me do the rest of the days if you would like. Having a gallery for each separate day might be a lot of pages considering there's a 100 so we want to make it a lot simpler.

**Comment by adriancancode** [comment]
That works with me.  But a drop down with 100 days?  Long list :laughing:

**Comment by EthanThatOneKid** [comment]
I think the best of both worlds could be 10 days of design submissions per page.

For example,
| URL | Description|
|---|---|
| acmcsuf.com/100daysofdesign[?page=0] | Days 1-10 |
| acmcsuf.com/100daysofdesign?page=1 | Days 11-20 |
| acmcsuf.com/100daysofdesign?page=10 | Days 91-100 |

**Comment by adriancancode** [comment]
^This works w/me.  How about you @26samaahmed ?

**Comment by 26samaahmed** [comment]
That works 👍

**Comment by adriancancode** [comment]
Maybe what i could do is have each day in a row with the submissions following the day title.

**Comment by adriancancode** [comment]
You get the submissions together and I'll start formatting how I want each day displayed?

**Comment by 26samaahmed** [comment]
The way I want this to look like is this:
Page 1 through 10 will have a row for each day like you mentioned and below each design we will mention the discord of the person who made it. I can get the designs and the people who made it and store it in a json file then you can format it however you would like if that sounds good.

**Comment by adriancancode** [comment]
@26samaahmed I'm gonna use a similar layout for this to how I did with the portfolio gallery.  Creating a branch for this right now.

**Comment by adriancancode** [comment]
Created branch feat/1098 for this

**Comment by 26samaahmed** [comment]
This is what I'm thinking the page should look like @adriancancode <br>
![MacBook Air - 7](https://github.com/user-attachments/assets/0876ccde-cb6a-4e07-8caa-bde741e15ac7)

**Comment by 26samaahmed** [comment]
Update: This page might be transferred to another project called **Gallery** that will showcase pages like every team's weekly pictures and 100 days of design challenge.
