### ISSUE TITLE
Events page flashback

### ISSUE THREAD

**Issue by adriancancode** [acmcsufoss/acmcsuf.com#1105]
### What's your idea?

On the Events Page for acmcsuf.com, we should have buttons and links to different past events, like one for the Spring 2024 Portfolio competition gallery that I created and a few for the photo galleries of all of our workshops from the past.

**Comment by 26samaahmed** [comment]
The events page is usually for creating reminders for future ACM workshops that are recorded via Google Calendar. I think creating links to past events like galleries will make it confusing to differentiate between past and future workshops. If people want the link to past events like the gallery page you created, it's on the acmcsuf.com/sitemap under 'Showcase' so this might be repetitive. If we make future galleries, we can add it to the sitemap page to avoid confusion on the events page. 

<img width="1440" alt="Screenshot 2024-07-17 at 2 36 23 PM" src="https://github.com/user-attachments/assets/5c79eccc-97d9-412e-a741-b211b4aab410">

**Comment by EthanThatOneKid** [comment]
Closed in favor of #1093.
