### ISSUE TITLE
"General Team" -> "General Board"

### ISSUE THREAD

**Issue by amyipdev** [acmcsufoss/acmcsuf.com#1109]
### What's your idea?

References on the Teams page to "General Team" should be replaced by "General Board". acmGeneral as a term hasn't been used much in a while, and while technically Event Coordinators and the like are not constitutionally part of General (although they could be), General Board feels more correct.

**Comment by thisguyblink** [comment]
General Team is shorter so it loads faster. If we change to General Board it might take longer for the page to load and people who visit might not like the longer load times. Also, we should abide by the Consitution, so we shouldn't include positions on the General Board that aren't actually on it.

**Comment by k4rni** [comment]
While I completely agree with your point of view towards the optimization of the website, I believe that we need to address the main issue at hand which is the terminology that is affecting the current situation. The event coordinator should be added to the general team to resolve the underlying problem that we are facing.

**Comment by 26samaahmed** [comment]
I agree with Karni and that way, we can keep the name as 'General team' for cohesiveness with the rest of the teams. It's implied that everyone on that page is on board so i personally think it makes sense to keep as General Team.

**Comment by NateGries** [comment]
While i understand your concern with the terminology regarding the general team, i think that a better course of action would be to add an amendment to our constitution in which we include the Event Coordinator position as part of the General Team.

**Comment by thisguyblink** [comment]
Nate I think there is a large disconnect of your understanding of the Constitution. It would take a while for the ammendment to pass through the House and Senate to then get approved by the President. Also, we should further attempt to optimize the title by making it a smaller font and by abbreviating it as G.T.

**Comment by karnikaavelumani** [comment]
Patrick I agree. We should optimize the codebase to simply remove all the CSS and JavaScript altogether! Vanilla HTML is the fastest and most lightweight language for webdev and we should use this to optimize our end user experience.

**Comment by NateGries** [comment]
While eliminating JavaScript and CSS would be effective in making the teams page more efficient, I believe that it would remove much needed functionality from the site. I suggest that we instead rewrite all code in a real language like C++.

**Comment by thisguyblink** [comment]
@26samaahmed  Can you refactor the codebase in C++? It should only take about a week, right?

**Comment by 26samaahmed** [comment]
If anyone has any jokes, I prefer this to be done over discord rather than on a serious issue.

**Comment by amyipdev** [comment]
> While i understand your concern with the terminology regarding the general team, i think that a better course of action would be to add an amendment to our constitution in which we include the Event Coordinator position as part of the General Team.

I would absolutely support doing this, although the Constitution uses the term General Board and, at least for Constitutional purposes, I recommend we keep that name. 

The issue was not removing Event Coordinators from there, but rather whether to use General Board vs General Team. My proposal was to keep ECs there and change the verbiage to General Board; I wouldn't support a proposal removing ECs from that section.

If there's interest, I can work on such a constitutional amendment to be noticed at the first General meeting and then voted on at the second meeting. Event Coordinators aren't mentioned in the Constitution at all; I could write them in as an appointed General Board position. For what it's worth, Webmaster isn't mentioned by name right now - constitutionally, they're part of the server team - and that could be changed since Webmaster responsibilities have even further diverged from Server Team. Requesting clarification from @26samaahmed on what she thinks of that, since right now Webmaster is technically an informal position (she's not a server team member), and it may be better to move www.acmcsuf.com-specific duties to a discrete position instead for clarity.

**Comment by 26samaahmed** [comment]
@amyipdev I think it makes sense for Webmaster to be mentioned by name constitutionally but not as a part of the server team since I am not involved in the server at all. The webmaster's current duty is maintaining the acmcsuf.com website and helping people contribute to it as it is our largest open source project.

**Comment by amyipdev** [comment]
That is exactly what I am proposing, separating it from servers entirely and placing it within General Board to match the current structure.

**Comment by NateGries** [comment]
wait who put webmaster in the server team? also, i think that if we want to make small changes like this then we can just change it in discord and how we address our board and roles, we don't have to follow the constitution so strictly nor update it for everything.

**Comment by amyipdev** [comment]
> wait who put webmaster in the server team?

Under the Constitution the duties encompassed by the webmaster are part of the Server Team.

ACM Constitution, Article III, Section 2(a): _The Dev Board and the Open Source Software Board shall determine the procedures for the appointment of an officer, or multiple officers, whose responsibilities shall additionally include maintenance of Chapter infrastructure **and official Chapter websites**. All officers appointed in this manner shall work closely together to integrate these procedures, and shall have overlapping responsibilities. These officers must already be officers, including Team Leads, of either the Dev Board or the Open Source Software Board._ 

> we don't have to follow the constitution so strictly nor update it for everything.

One of the main points of the recent Constitution changes was to have it match our actual operations. In the rare case SLL were ever to get involved it makes things cleaner, plus can help in relations with other organizations.
