### ISSUE TITLE
Icons aren't visible on dark mode when events are created

### ISSUE THREAD

**Issue by 26samaahmed** [acmcsufoss/acmcsuf.com#1114]
### What happened?

Look at photo for reference:
![image](https://github.com/user-attachments/assets/b7b7f433-42b7-4bf9-a4b7-a25ec502713d)

**Comment by tomasohCHOM** [comment]
I believe this bug should be of higher priority since it's an issue that a lot of people will end up encountering eventually. I think we should resolve this asap, I will try to fix it right now.
