### ISSUE TITLE
Add a nav bar link to the sitemap

### ISSUE THREAD

**Issue by adriancancode** [acmcsufoss/acmcsuf.com#1126]
### What's your idea?

Now that we have the sitemap published, we should have a link somewhere on the landing page to it, so newcomers can easily access it and find out all the amazing pages we have.  I'm thinking of putting it on the nav bar, but if any of yall have a better idea on where I should put it, let me know.

**Comment by 26samaahmed** [comment]
It's on the footer so there's no need for it being on the nav bar as well

**Comment by adriancancode** [comment]
Sweet!
