### ISSUE TITLE
SvelteKit port bugs

### ISSUE THREAD

**Issue by ghost** [acmcsufoss/acmcsuf.com#148]
### What happened?

Nav Bar: Active pages don't keep highlighted text
Homepage: Path section redirect doesn't show path sections properly (ex: clicking algo -> #algo in paths page)

**Comment by EthanThatOneKid** [comment]
Created separate issues (#150 and #151) for these two bugs you’ve found. Let’s continue any related discourse on those issues. Locking this now.
