### ISSUE TITLE
Create Discord text channel on issue creation

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#162]
## Background

Our team uses Discord for casual chatting and brain-storming conversations. We currently manually create text channels for every open issue on GitHub so we can have a casual place to chat specifically about that issue.

## Implementation

Instead of manually creating the text channel, we can create a workflow that creates one when a new issue is created on GitHub. The workflow would also start the conversation with a link to the issue and pin the message.

**Comment by anhduy1202** [comment]
Can we create a bot to do that? or does Github provides any functionalities similar to that

**Comment by EthanThatOneKid** [comment]
> Can we create a bot to do that? or does Github provides any functionalities similar to that

Yes, we can write a NodeJS script that uses the [Discord.js](https://github.com/discordjs/discord.js) library to handle all the operations for us.

#### Script Outline

1. Authenticate the Discord bot session.
2. Add the new text channel under the correct category in our server.
3. Send the link to the new issue in the newly-created text channel.
4. Pin that original message.
5. Exit.

This script can be called by a workflow file each time a new issue is opened (see <https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issues>).

**Comment by anhduy1202** [comment]
that sounds like a great side-projects, we can work on that 👀

**Comment by EthanThatOneKid** [comment]
The bot is working now ([successful workflow run](https://github.com/EthanThatOneKid/acmcsuf.com/actions/runs/1400979421)) as of commit <https://github.com/EthanThatOneKid/acmcsuf.com/commit/c376834e0b0a96378f3bbad0505fbf42dfadb2a3>!

### Feature History

- We started writing the solution in @anhduy1202's shared Replit workspace.
- Then, we published a buggy solution in PR #165. 
- Finally, we pushed commit <https://github.com/EthanThatOneKid/acmcsuf.com/commit/c376834e0b0a96378f3bbad0505fbf42dfadb2a3> to finish it off.

**Comment by EthanThatOneKid** [comment]
Closed by <https://github.com/EthanThatOneKid/acmcsuf.com/commit/c376834e0b0a96378f3bbad0505fbf42dfadb2a3>.
