### ISSUE TITLE
Large gap in officer list

### ISSUE THREAD

**Issue by ghost** [acmcsufoss/acmcsuf.com#223]
### What happened?

![image](https://user-images.githubusercontent.com/54593375/141236144-52779735-2f9d-444b-bcc2-d7e3b7d3b58c.png)
There's a large gap between the header and the officer list.

**Comment by jaasonw** [comment]
```[6:15 PM] Mike (he/him): this is resolved. reason: i've come to terms with the space and im ok with it lmfao```
