### ISSUE TITLE
Events: Clicking "Join" navigates to 404

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#292]
### What happened?

Currently when the visitor clicks a "Join" button for an event that links to another `acmcsuf.com`-hosted page, they encounter the 404 error page. We want the visitor to be redirected to the appropriate page.

**Comment by diamondburned** [comment]
That might be a regression in commit a2f8dd7936b42199bcd52f1c0f5c8ed78eab2c74:

```diff
-      const meetingLink = isZoomMeeting ? rawLocation : '/discord';
-      const customLocationName = parsedDescription['ACM_LOCATION'];
-      const location = isZoomMeeting ? 'Zoom' : customLocationName ?? rawLocation;
+      const customLocationName = parsedDescription['ACM_LOCATION'] ?? rawLocation;
+      const location = isZoomMeeting ? 'Zoom' : customLocationName;
+      const meetingLink = isZoomMeeting ? rawLocation : (location.startsWith('https://') ? location : "/discord");
```

**Comment by diamondburned** [comment]
The point of the change was so that `location` can be used as a custom URL to the Join button, so it's probably better to actually fix the problem rather than just reverting the change.

**Comment by EthanThatOneKid** [comment]
> The point of the change was so that `location` can be used as a custom URL to the Join button, so it's probably better to actually fix the problem rather than just reverting the change.

I do not intend on reverting that change.

**Comment by EthanThatOneKid** [comment]
I believe it is expected behavior for the "Join" button to navigate the user to an external website. Opening the join link in a new tab instead of redirecting the user in their existing tab (see #293) might resolve this bug.
