### ISSUE TITLE
Events: Off-center event datetime on some devices

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#334]
On my phone, the date and times for the event items are right-aligned for some reason.

### Screenshot

![6F884D95-1DAC-4935-A5D6-0B8807157A25](https://user-images.githubusercontent.com/31261035/158015556-18054873-1029-4d3d-b8e7-d39f0bfd83b2.jpeg)

**Comment by jaasonw** [comment]
it's fixed by idk what
