### ISSUE TITLE
can u make all links in events open in a new tab

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#346]
### What's your idea?

[10:54 AM] jasonw: can u make all links in events open in a new tab pls thx
[10:55 AM] EthanThatOneKid: Good idea
[10:56 AM] EthanThatOneKid: Which links were you talking about
[10:56 AM] jasonw: all of them
[10:56 AM] jasonw: clicking anything on that page should never make me leave

**Comment by EthanThatOneKid** [comment]
I was thinking that it may be possible to use [JSDOM](https://github.com/jsdom/jsdom) to parse the HTML from Google Calendar, giving us the ability to forcefully assert `target="_blank"` for all instances of `<a>` tag.

See <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#external_links_and_linking_to_non-html_resources>.

**Comment by EthanThatOneKid** [comment]
> [3:47 PM] diamond (they/them): have you tried: 🌈 regex 🌈
> [6:17 PM] Ethan (he/him/Webmaster): Is there a magic pattern for this replacement? Problem I had in mind is that the input html is might not be predictable enough. It is probably possible in regex tho ty for the suggestion I’ll look more into it this weekend
> [6:26 PM] diamond (they/them): I can whip something up; it's not like we gotta deal with mega complex HTML
> [2:20 AM] diamond (they/them): https://go.dev/play/p/_wxztmECmEQ 

@diamondburned suggested via Discord that we instead try to use _regular expressions_ to prevent over-complicating this process using JSDOM. I initially chose JSDOM to get rid of any doubt in case there are any cases where regular expressions would not be able to replace each link properly, but the regular expression that @diamondburned produced passes several important test cases that we need. So, the regular expression might be the best way to go!

**Comment by EthanThatOneKid** [comment]
> [5:14 PM] Ethan (he/him/Webmaster): Diamond’s Go code:
> ```go
> package main
> 
> import (
>     "fmt"
>     "regexp"
>     "strings"
> )
> 
> func main() {
>     var re = regexp.MustCompile(`(?m)<a.*href=".*">`)
>     var str = `<a href="joe mama">
> <a>
> <a title="hhhh" href="joe mama">
> asdasda
> `
> 
>     str = re.ReplaceAllStringFunc(str, func(match string) string {
>         if !strings.Contains(match, `target="`) {
>             match = strings.TrimSuffix(match, ">") + ` target="_blank">`
>         }
>         return match
>     })
> 
>     fmt.Println(str)
> }
> ```
> [6:07 PM] Ethan (he/him/Webmaster): Rewritten in TypeScript: 
> ```ts
> function assertHtmlHasAllExternalLinks(html: string): string {
>     return html.replaceAll(/<a.*href=".*">/gm, (match: string): string => {
>         if (match.includes("target=\"_blank\"")) return match;
>         return match.replace(/target="_.*"/g, "").slice(0, match.length - 1) + " target=\"_blank\">";
>     });
> }
> 
> console.log(assertHtmlHasAllExternalLinks(`<a href="joe moma">
> <a>
> <a title="hhh" href="joe moma">
> <a title="hhh" target="_self" href="joe moma">
> <a title="hhh" target="_blank" href="joe moma">
> asdasda
> `));
> ``` 
> [6:07 PM] Ethan (he/him/Webmaster): ^ Untested written in discord on mobile
> [4:47 PM] Joel Anil John (he/him): Wait so what is the purpose of the code?
> [5:55 PM] Joel Anil John (he/him): Also, would event-item.svelte be the ideal place to implement this function?
> [7:54 PM] Ethan (he/him/Webmaster): Sorry for not replying sooner, but the purpose of the code is to make sure that all of the links in the google calendar description are external links. We can pass the html from the google calendar description through this function and it will make sure any occurrences of a link will be external as expected
> [7:56 PM] Ethan (he/him/Webmaster): We would do this text transformation on the backend before it hits the client malformed, likely within the makeAcmEvent function 
> [9:10 PM] Joel Anil John (he/him): ahh gotcha
> [9:10 PM] Joel Anil John (he/him): so we're not gonna need JSDOM then?
> [9:40 PM] Ethan (he/him/Webmaster): Yes, the regex solution is a replacement for the jsdom idea. Should be much more efficient and will take up 0 dependencies.
> [9:40 PM] Ethan (he/him/Webmaster): I should write up another comment on GitHub to reflect this

Above is a conversation from Discord about our current plan to fix this issue. In our fix, we can add a test for the `assertHtmlHasAllExternalLinks` utility function in [`/src/lib/ical/utils.test.ts`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/4f46f7c1b4843f9535c01f19ac3e715d18b01027/src/lib/ical/utils.test.ts) with our input being the sample text used in the above example code.

**Comment by jaasonw** [comment]
hey wait a minute, i know we spent all this time writing the actual function but like, did we ever bother to call it in events cus the board applications dont open in a new tab LOL
