### ISSUE TITLE
Button hover effect

### ISSUE THREAD

**Issue by ghost** [acmcsufoss/acmcsuf.com#347]
### What happened?

i recently heard that the plan is to change text color on button hover rather than background-color of the button on button hover. i disagree with this because it's not a good UX choice due to the colors we use.

as it currently stands, the colors we use in our design language is bad for accessibility on dark backgrounds (one of the reasons why I strayed away from dark mode at the early stages of the website) due to how saturated the colors are. relating to this, acmBlue does not look good on acmDark because both colors are too dark. this is why I designed the buttons to change the background color to acmBlue on hover.

i recommend that for buttons, background-color change should be the hover effect.

**Comment by EthanThatOneKid** [comment]
Followed up in #647.
