### ISSUE TITLE
Officer Automation: Add more detailed instructions for uploading officer picture

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#348]
### What's your idea?

We require that all images uploaded to the site adhere to the design standard of centering the officer's face in a glowy, diamond-shaped frame. The resulting image should be transparent and exported as PNG at 460x460px.

### Sample Diamond Cutout

![image](https://user-images.githubusercontent.com/31261035/158543661-a5a4d3f0-05cd-4cc3-b6fc-6f833b723812.png)

Suggested by @diamondburned via Discord.

**Comment by alvin-tosh** [comment]
```img {
  -webkit-mask:url(https://i.ibb.co/mBrmH0k/Mf15d.png) center/contain no-repeat;
  opacity: 0.5;
}
```
this is the purpose of mask; to fit the section designated for it.:point_up_2:

```img {
    max-width:460px;
    max-height:460px;
}
```
Keep in mind that this :point_up_2: also pertains to how the pic will be displayed. If you wish to reduce the image's real width and height to save space on the server, you'll need to use uploading plugins that include scaling settings. 


```img {
    -webkit-mask:url(https://i.ibb.co/mBrmH0k/Mf15d.png) center/contain no-repeat;
    opacity: 0.5;
    max-width:460px;
    max-height:460px;
}
```

:crossed_fingers: Reckon this should work. :smile:

**Comment by diamondburned** [comment]
This could work, but we might be better off using `<svg>` and CSS `mask` for this, as that's not deprecated. 

Relevant links:

- https://css-tricks.com/clipping-masking-css/ (section "Masking" and "Using clip-path with an SVG-defined \<clipPath\>")
- https://developer.mozilla.org/en-US/docs/Web/CSS/mask

**Comment by diamondburned** [comment]
> ![image](https://user-images.githubusercontent.com/31261035/158543661-a5a4d3f0-05cd-4cc3-b6fc-6f833b723812.png)

Apparently this image is off-centered in all directions.

![image](https://user-images.githubusercontent.com/8463786/193452616-99407061-e32a-42d3-bcab-746c7c52280b.png)

**Comment by diamondburned** [comment]
I've made a prototype SVG here:

![acm-diamond-whole](https://user-images.githubusercontent.com/8463786/193455604-08613a3c-81c0-4b5a-bafa-0934fd4eb27f.svg)

It contains a path for the base of the diamond and a path for the glow (drop shadow). It's in Inkscape SVG, so certain things may not open it properly.

**Comment by diamondburned** [comment]
I think it's a good idea if we can deprecate `./static/assets/authors` in favor of `./static/assets/members` or `./static/assets/authors-uncropped`, which will contain uncropped images of all board members. This could be used once the SVG is ready.

**Comment by EthanThatOneKid** [comment]
A Discord slash command is intended to be used to trigger a [GitHub Workflow](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) that automates opening a PR instead of an [issue template](https://github.com/EthanThatOneKid/acmcsuf.com/blob/cfb616e655f2a70b284e6f7b8426bf32c15eb4b7/.github/ISSUE_TEMPLATE/officer_update_request.yaml).

**Comment by EthanThatOneKid** [comment]
Related: #546, #213.
