### ISSUE TITLE
Bump `package.json` version to "3.0.0"

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#393]
### What's your idea?

Before releasing [v3.0](https://github.com/EthanThatOneKid/acmcsuf.com/milestone/3), remember to bump the version in our `package.json`.

Related: #392.

**Comment by k4rni** [comment]
Resolved by <https://github.com/EthanThatOneKid/acmcsuf.com/pull/540/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3>.
