### ISSUE TITLE
I feel like default location should no longer be "Hosted on Discord"

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#416]
### What happened?

![image](https://user-images.githubusercontent.com/8981287/161177102-ba9cc951-908e-4d78-b428-ff6d2617c9ee.png)

**Comment by EthanThatOneKid** [comment]
The default value there should actually say _TBD_ instead of _Hosted on Discord_ according to @karnikaavelumani. Good catch!
