### ISSUE TITLE
bad contrast on 404 page dark mode

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#417]
### What happened?

![image](https://user-images.githubusercontent.com/8981287/161234327-60665875-73a1-48dc-8a04-2b082c3ce39b.png)

**Comment by Angel-Armendariz** [comment]
This is an image correct? Could we possibly create another 404 error with Frank that is dark mode friendly and make it so it swaps between the two when switching modes?

**Comment by jaasonw** [comment]
yes

**Comment by jaasonw** [comment]
still waiting for @mikeploythai after 2 weeks

**Comment by k4rni** [comment]
what's the progress on this?

**Comment by Angel-Armendariz** [comment]
Basically just gotta add some margin to the image, I'll hop on now I was just busy being thrown around by my finals today 

> what's the progress on this?
