### ISSUE TITLE
The ACMCSUF Logo disappears when navigating to a URL with multi-level subdirectory 

### ISSUE THREAD

**Issue by NLTN** [acmcsufoss/acmcsuf.com#429]
### What happened?

For example, when I go to [https://acmcsuf.com/paths/ToTheMoon](https://acmcsuf.com/paths/ToTheMoon), the logo on the navigation bar is gone.
<br />

<img src="https://github.com/NLTN/Assets/blob/main/acmCSUF/issues/logo_disappears.png?raw=true">

**Comment by jaasonw** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8981287/163498225-faa7677c-b046-4060-8678-0314d41550bd.png">

whoever wanna fix this probably just needa add a slash to the front of the url here
https://github.com/EthanThatOneKid/acmcsuf.com/blob/main/src/lib/components/sections/navbar.svelte#L34

**Comment by diamondburned** [comment]
cc @hhoang91

**Comment by hhoang91** [comment]
Could you please assign me to this issue?
