### ISSUE TITLE
Blog logo unreadable when in dark mode

### ISSUE THREAD

**Issue by charliettaylor** [acmcsufoss/acmcsuf.com#430]
### What happened?

The README logo is unreadable in dark mode, and the borders around the articles also disappears.

Light
![image](https://user-images.githubusercontent.com/56566188/163342853-702fa856-15d9-4ff5-a2ce-0ab23d7263b5.png)
Dark
![image](https://user-images.githubusercontent.com/56566188/163342784-f148c52d-bbed-4ec7-8b2f-905749f6d7b3.png)

**Comment by jaasonw** [comment]
Fixed in #406

**Comment by jaasonw** [comment]
@mikeploythai 😠

**Comment by ghost** [comment]
> @mikeploythai 😠

am busy will send out something this weekend
