### ISSUE TITLE
dark mode toggle button delayed loading

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#452]
### What happened?

![](https://i.imgur.com/IteWqyQ.gif)

**Comment by EthanThatOneKid** [comment]
Thank your for filing this bug report! The plan will be to have this triaged and then assigned to a volunteer contributor.

**Comment by EthanThatOneKid** [comment]
The loading of this button is necessary in order for it to conditionally render only for users with JavaScript enabled. #474 effectively voids this issue by adding a subtle fade-in effect to ease the jarringness of the behavior recorded above.
