### ISSUE TITLE
Change Paths to Teams

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#470]
### What happened?

Replace all path badges with newly updated Figma assets. Descriptions must include "Chapter" and must be described as **Teams** rather than as Paths. Include new AI team.

Figma Library: https://www.figma.com/file/dHwyipuuf90ZVzFlHKS3AC/Design-Library?node-id=0%3A1 

| Outdated | Updated |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/60043611/168458548-717e369a-c03d-4f58-9163-71f343e18367.png) | ![image](https://user-images.githubusercontent.com/60043611/168458542-47be888c-231a-476b-a8f1-6e2d0bb1494e.png) 
| ![image](https://user-images.githubusercontent.com/60043611/168458582-dd9d3524-c088-41cb-8210-f646e78423b2.png) | ![image](https://user-images.githubusercontent.com/60043611/168458591-ee0ab08c-313e-44c3-9333-7fc2aa0806c7.png)
| ![image](https://user-images.githubusercontent.com/60043611/168458600-3d86e85b-d1c7-464b-8694-b0cf348cf527.png) | ![image](https://user-images.githubusercontent.com/60043611/168458613-3fc83a23-5555-4bf4-8712-2dfbbb27cc41.png)

**Comment by EthanThatOneKid** [comment]
There are still a number of occurences of the word "path" in the codebase, usually using the legacy `$lib/public/legacy/acm-paths` library. For example, see [src/lib/components/toaster/toasts.ts](https://github.com/EthanThatOneKid/acmcsuf.com/blob/933fa16bad61ef85c224950614c6d67edaa9cf6b/src/lib/components/toaster/toasts.ts).

**Comment by EthanThatOneKid** [comment]
Visually speaking, this issue was resolved in #518.
