### ISSUE TITLE
Blog: acmcsuf.com/blog.xml is down! 😿

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#473]
### What happened?

I was trying to see the latest blog posts on acmcsuf.com/blog when all of a sudden I was met with this terrible error message:

### Proof of Incident

![image](https://user-images.githubusercontent.com/31261035/168763073-60619bc1-ad77-4716-8f72-efe0b1b3e230.png)

**Comment by k4rni** [comment]
D:

**Comment by EthanThatOneKid** [comment]
Don't tell me... the plaintext endpoints are also down?! D:

![image](https://user-images.githubusercontent.com/31261035/168770928-879278ac-b5e1-4268-a1c8-630060d81538.png)

**Comment by jaasonw** [comment]
![image](https://user-images.githubusercontent.com/8981287/169606761-7b7eb19b-502d-4a7e-a13e-933282a8bbb6.png)

**Comment by jaasonw** [comment]
![image](https://user-images.githubusercontent.com/8981287/190325022-b348c2ad-3480-46af-bdb6-460b4621b4b9.png)

seems to work for me, is this closeable?

**Comment by EthanThatOneKid** [comment]
The `/blog/:id.txt` endpoint was fixed in mega-PR #577.
