### ISSUE TITLE
node_modules is missing

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#478]
### What happened?

it does not run when i do npm run dev

**Comment by EthanThatOneKid** [comment]
To install the dependencies, please run `npm i`. NPM is normally installed along with Node.js (`node`). For more information, refer to "Getting Started" step 3 in our [`CONTRIBUTING.md`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/6b5b45ac4431fa79f27bf24a277b39086c588cce/CONTRIBUTING.md#getting-started-) documentation.

**Comment by EthanThatOneKid** [comment]
> [11:59 PM] Justin: node modules is where npm will put all your packages for your application. Typically, this folder is quite large (upwards for 15mb just for boilerplate) and therefore it is expensive to keep in source control
[11:59 PM] Justin: so they add this folder to .gitignore which tells your source control git to ignore it and thats why that fellow didn't see node modules in his clone of the repository

@JustinStitt explained via Discord

**Comment by EthanThatOneKid** [comment]
Alternative V8 runtimes to Node.js, such as **Deno** (<https://deno.land/>), are capable of installing all dependencies when the program is initially run, however.

Since this project is built on SvelteKit which relies on Node.js, I doubt we will be able to get rid of the installation step without migrating the website away from SvelteKit.

**Comment by jaasonw** [comment]
ok but what does @JustinStitt know he's a c++ fan : )

**Comment by EthanThatOneKid** [comment]
> node_modules is missing

Context: <https://twitter.com/roxkstar74/status/1526937921688944646>

**Comment by EthanThatOneKid** [comment]
> ok but what does @JustinStitt know he's a c++ fan : )

He’s recently worked on [acmBall](https://github.com/AaronLieb/acmBall), which utilized NPM.
