### ISSUE TITLE
Blog: Show more related links at bottom of each post

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#482]
### What's your idea?

Currently, the only external link (opens in a new tab) awaiting the reader at the bottom of each blog post is our `.txt` easteregg,
![image](https://user-images.githubusercontent.com/31261035/170389428-a4214697-9ae3-4dc3-a43d-2b4ddbb5dbdd.png)

I want to add at least one more link to the original discussion on GitHub. Looking for more ideas of links to add to the bottom of each blog post. 

Mock-up (messing with the HTML in my browser):
![image](https://user-images.githubusercontent.com/31261035/170389850-b9f95e0e-53ea-4395-894f-a22de7a51f72.png)

**Comment by k4rni** [comment]
Ok I've been thinking and I just realized after looking through some example blogs/news sites, we never indicate when these posts are published! (or maybe we do and I'm blind so correct me if I'm wrong haha). 

My idea is something of the sorts:
![image](https://user-images.githubusercontent.com/60043611/170411705-b20b7f70-c4a5-4849-b115-e8ec1ad1cac3.png)

**Comment by jaasonw** [comment]
> Ok I've been thinking and I just realized after looking through some example blogs/news sites, we never indicate when these posts are published! (or maybe we do and I'm blind so correct me if I'm wrong haha).
> 
> My idea is something of the sorts: ![image](https://user-images.githubusercontent.com/60043611/170411705-b20b7f70-c4a5-4849-b115-e8ec1ad1cac3.png)

I added the publish date to https://github.com/EthanThatOneKid/acmcsuf.com/pull/481

**Comment by jaasonw** [comment]
I was thinking maybe we could add a link to the github discussion so people can comment on it "Discuss on Github" or something?

**Comment by k4rni** [comment]
oh yeah ethan informed me. that's a cool addition too maybe

**Comment by k4rni** [comment]
Resolved by #481.
