### ISSUE TITLE
Workflows: PAT required for some steps

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#490]
### What happened?

Some common workflow steps, such as generating a PR, require a personal access token (PAT) in order to succeed.

Here the link to a workflow step which is hypothesized to have failed due to this issue: https://github.com/EthanThatOneKid/acmcsuf.com/runs/6622054928?check_suite_focus=true#step:8:89

**Comment by jaasonw** [comment]
assigning this to ethan bcus it involves administrative main repo stuff

**Comment by EthanThatOneKid** [comment]
Resolved by #548.
