### ISSUE TITLE
Update Sveltekit Version

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#502]
### What happened?

Update acmcsuf.com to latest sveltekit version in preparation for sveltekit v1.0

In relation to #500

**Comment by EthanThatOneKid** [comment]
Accidentally closed in recent PR that does not resolve the issue.

**Comment by EthanThatOneKid** [comment]
Test: Reopening this issue to check #588.

**Comment by EthanThatOneKid** [comment]
> Test: Reopening this issue to check #588.

Resulting create_channel job: <https://github.com/EthanThatOneKid/acmcsuf.com/actions/runs/3107955502/jobs/5036629948>.

Now closing to successfully archive this issue.

**Comment by EthanThatOneKid** [comment]
> Now closing to successfully archive this issue.

The resulting close_channel job was a success!
<https://github.com/EthanThatOneKid/acmcsuf.com/actions/runs/3107970187>
