### ISSUE TITLE
cannot see navbar separation on dark mode

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#511]
### What happened?

![image](https://user-images.githubusercontent.com/8981287/185776569-63314560-2cff-453f-a1f1-fda0201a8159.png)
![image](https://user-images.githubusercontent.com/8981287/185776599-30b9405e-e327-40ca-80d3-d01e032e056f.png)

**Comment by Rico-Smit** [comment]
Hi jaasonw, i would love to assist with this. 😁
