### ISSUE TITLE
make events show end time

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#521]

**Comment by rashmisubhash** [comment]
Can I take up this issue?

**Comment by EthanThatOneKid** [comment]
> Can I take up this issue?
> 
> 

Hi, @Rashmibss! You are totally welcome to take up this issue. To get started, I would refer to our `CONTRIBUTING.md` and `GETTING-STARTED.md` if you haven't already.

If you are in our Discord server, please contact `@Webmaster` to gain access to the  website-related channels.

**Comment by rashmisubhash** [comment]
Okay. Do I have to add the end time along with the start time here?

![image](https://user-images.githubusercontent.com/29196787/187621546-a8506d19-158a-484f-a04d-590d5cb1a685.png)

**Comment by EthanThatOneKid** [comment]
> Okay. Do I have to add the end time along with the start time here?
> 
>

Yes, you will find the relevant files in `/src/lib/components/events`.

**Comment by rashmisubhash** [comment]
Yes, I got the file where the changes are needed. Events JSON has one of the params as `date: "2022-09-02T15:00:00-07:00[America/Los_Angeles]"`

Should I take `07:00` as the end time? 
If so, it is not within 24 hours. 
Or should I directly take it as `7:00 PM`

**Comment by EthanThatOneKid** [comment]
You should directly format it to `7:00 PM`. Thank you!
