### ISSUE TITLE
ACM Intro Quiz

### ISSUE THREAD

**Issue by AlanCortez1337** [acmcsufoss/acmcsuf.com#527]
### What's your idea?

I want to make a matching app that helps choose possible events to go to for new people. While showing off resources for that and ways they can join/help the ACM board.

My Idea is to be directed to a quiz which the responses will loosely match the person to a current team. Once matched the user will be able to click on the teams for more information about their specific events and how to get started on their own. Additionally there should be a section where people can find a way to help others through ACM.

A figma mock up design can be found [here](https://www.figma.com/file/SoFJesCVZd0bytyJ0FodLr/Buzzfeed-quiz?node-id=0%3A1).

**Comment by EthanThatOneKid** [comment]
Resolved by #528.
