### ISSUE TITLE
events page loads slow

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#530]
currently the events page loads really slow. this is because the following steps have to occur

1. wait for the serverless function to cold start
2. wait for the calendar api to return a response
3. generate the html page with the events already loaded

this creates a bottleneck where the api call essentially blocks the page load until it completes

i suggest changing the process to either load the events asynchronously as to not block the page load

1. load the page without the events
2. call the calendar api after or during the page load
3. add the events to the page afterwards

**Comment by k4rni** [comment]
May I see like a video because I'm having a hard time understanding since it loads decently fast for me.

**Comment by EthanThatOneKid** [comment]
To improve the load time on the n+1 visit, try toggling the bool found on <https://github.com/EthanThatOneKid/acmcsuf.com/blob/44a2435b0cf7e7bf5483d0197fc2dfc961082613/src/routes/events/index.json.ts#L8>

**Comment by EthanThatOneKid** [comment]
This recent improvement of SvelteKit's <https://kit.svelte.dev/docs/load#streaming-with-promises> might be helpful here:

> Promises at the _top level_ of the returned object will be awaited, making it easy to return multiple promises without creating a waterfall. When using a server `load`, _nested_ promises will be streamed to the browser as they resolve. This is useful if you have slow, non-essential data, since you can start rendering the page before all the data is available.

> On platforms that do not support streaming, such as AWS Lambda, responses will be buffered. This means the page will only render once all promises resolve.

> Streaming data will only work when JavaScript is enabled. You should avoid returning nested promises from a universal `load `function if the page is server rendered, as these are not streamed — instead, the promise is recreated when the function re-runs in the browser.
