### ISSUE TITLE
Dedicate team data for `/quiz`

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#538]
### What happened?

The data that currently supplies the `/quiz` page uses a legacy constant variable that should no longer be edited. A new "teams"-branded constant variable would suit our needs. In the meantime, the changes made to the constants in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/528/files#diff-9c15f43b01f835ed6e77ac6a576fdbcd72cdc5a6e9a928d1b3d153a61a6605d8> should be moved to another variable in `/src/lib/quiz/`.

**Comment by k4rni** [comment]
Resolved by #591.
