### ISSUE TITLE
Should all title headers be {Page} | ACM at CSUF or ACM at CSUF | {Page} ?

### ISSUE THREAD

**Issue by erwinmedina** [acmcsufoss/acmcsuf.com#560]
### What happened?

As i was fixing [Issue 522](https://github.com/EthanThatOneKid/acmcsuf.com/issues/522), I came across inconsistencies among different titles and wasn't sure what looked right.

My solutions were:
Option 1 - `ACM at CSUF | {Page}`
Option 2 - `{Page} | ACM at CSUF`

My issue with option 2 was the 404 page.
`404 | ACM at CSUF` doesn't read right to me compared to `ACM at CSUF | 404`.
But maybe it does and i'm just being weird about it. 
Any recommendations, ideas, or solutions would be very much appreciated.

![Screen Shot 2022-09-13 at 11 18 10 PM](https://user-images.githubusercontent.com/10971284/190074677-d6a7cda4-baf9-4c8e-8d24-2242ef705d8a.png)
![Screen Shot 2022-09-13 at 11 18 38 PM](https://user-images.githubusercontent.com/10971284/190074830-9b013330-9d07-4960-95f1-4e899edbf8e0.png)
![Screen Shot 2022-09-13 at 11 19 15 PM](https://user-images.githubusercontent.com/10971284/190075025-cb30075e-d998-4532-86b8-6572d8d7211b.png)
![Screen Shot 2022-09-13 at 11 19 52 PM](https://user-images.githubusercontent.com/10971284/190075074-5d507144-f35f-4728-994c-1c472ace76ac.png)

**Comment by jaasonw** [comment]
closed by https://github.com/EthanThatOneKid/acmcsuf.com/pull/565 and https://github.com/EthanThatOneKid/acmcsuf.com/pull/562
