### ISSUE TITLE
Provide download link for Git

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#584]
We should probably provide a link to the actual download site for Git [in `GETTING_STARTED.md`].

_Originally posted by @karnikaavelumani in https://github.com/EthanThatOneKid/acmcsuf.com/pull/577#discussion_r977856574_

**Comment by amanda-mcmullin** [comment]
This seems rather straight forward.  I would like to try it!

**Comment by erwinmedina** [comment]
I'm sorry, this one ?
https://git-scm.com/downloads

**Comment by EthanThatOneKid** [comment]
> I'm sorry, this one ? https://git-scm.com/downloads

Thanks, that one will do the trick!

**Comment by erwinmedina** [comment]
Closed by pull request #652.
