### ISSUE TITLE
acmcsuf.com/blog.txt does not show emojis

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#622]
### What happened?

Emojis on acmcsuf.com/blog cannot be replicated in the blog.txt and are replaced by random characters. 

Current:
blog | txt
---|---
<img width="164" alt="image" src="https://user-images.githubusercontent.com/60043611/196569918-adaee14c-1fb0-42fb-9663-1eccfa7997ae.png">|<img width="194" alt="image" src="https://user-images.githubusercontent.com/60043611/196569961-fd3826cb-cfe1-46a5-bf71-d53b5e5ba411.png">

Instead, blog.txt should display the title name of the emojis.

Suggestion:
emoji | txt
---|---
❤️| <img width="76" alt="image" src="https://user-images.githubusercontent.com/60043611/196572509-2c403b10-98e4-48ee-9db9-8597c41bb556.png">

**Comment by k4rni** [comment]
As through further discussion, the conversion of our blogs to text files not only retains the simplicity of the text presented, but it also serves as an interesting Easter egg to our website. However, if the plaintext is ever copied and reopened, the emojis (if changed) will not properly render unless in unicode.

For those of you interested in converting emojis into text, feel free to check out: https://github.com/ArkinSolomon/discord-emoji-converter/blob/master/emojis.json

**Comment by EthanThatOneKid** [comment]
> [karnikaavelumani](https://github.com/karnikaavelumani) closed this as [completed](https://github.com/EthanThatOneKid/acmcsuf.com/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted)

We expect to continue using Discord as our primary mode of communication. Discord emoji names are still compliant when copying an entire plaintext blog post and pasting on Discord. 

> However, if the plaintext is ever copied and reopened, the emojis (if changed) will not properly render unless in unicode.

If we wish to retain the original emoji encoding, this could be addressed by, as part of resolving _this issue_, allowing the visitor to pass a URL query parameter (e.g. `?d`) to let our plaintext endpoint know whether or not emojis should be replaced with their Discord emoji name equivalent.
