### ISSUE TITLE
Blog: Known author name links to incorrect GitHub URL

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#650]
### What happened?

<img width="599" alt="image" src="https://user-images.githubusercontent.com/31261035/198935207-8b465f84-73bf-43ee-bc02-b6b4b170278c.png">

Note: The name "Ethan Davidson" is unexpectedly prefixed with `@` and incorrectly links to <https://github.com/Ethan%20Davidson>.

Related: #488.

### Recommendation

For blog post authors who have their GitHub username stored in `/src/lib/public/board/data/officers.json`, we like to show the author's full name where possible without a prefix of `@`, but still linking to the appropriate GitHub profile. If the username is not found within `/src/lib/public/board/data/officers.json`, then we should show the given GitHub username prefixed with `@`.

**Comment by logicalahara** [comment]
@EthanThatOneKid, would love to contribute to this, please assign this to me

**Comment by logicalahara** [comment]
@EthanThatOneKid I'm not sure this project is participating in hacktoberfest.

Will you please participate (if not) and add 'hacktoberfest' label to this issue ?

**Comment by EthanThatOneKid** [comment]
> @EthanThatOneKid, would love to contribute to this, please assign this to me

@logicalahara, thank you for volunteering!

For this issue, I’d like to see an edit made to the `BlogPost` type to optionally include the author’s full name as a new property, `fullName?: string;`. 

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/d48a1c150dc243e840cc24611d0f54906b81c640/src/lib/public/blog/types.ts#L15-L19>

Then, please take a look at this code. 

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/d48a1c150dc243e840cc24611d0f54906b81c640/src/lib/server/blog/posts.ts#L72-L105>

Use the `getOfficerByGhUsername` function to set the new “fullName” property of the return value above. 

Once you have `BlogPost.fullName`, you may use a Svelte [if-else block](https://svelte.dev/tutorial/else-if-blocks) to check if `.fullName` is undefined and render the desired information. 

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/d48a1c150dc243e840cc24611d0f54906b81c640/src/routes/(site)/blog/%5Bid%5D/%2Bpage.svelte#L22-L31>

> Will you please participate (if not) and add 'hacktoberfest' label to this issue ?

Thank you for bringing Hacktoberfest to this repository for 2022! I will add the `hacktoberfest-accepted` label to your PR.
