### ISSUE TITLE
Remove drop-shadow border in light mode

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#654]
### What happened?

The blog drop-shadow border is inconsistent in light mode and dark mode. The outer box shadow is apparent in light mode but not apparent in dark mode. The shadow should either be removed in light mode (preferred) or added in dark mode.

light mode | dark mode
---|---
![image](https://user-images.githubusercontent.com/60043611/198967281-1f45b55b-c6f4-4829-96ab-227998a7f80d.png)|![image](https://user-images.githubusercontent.com/60043611/198967561-2d7ec275-5c2d-43c9-aa7c-df678bab0cd3.png)

**Comment by nishtha53** [comment]
can i work on this issue?

**Comment by k4rni** [comment]
@erwinmedina I recall you received some comments from @jaasonw. Since this issue is still open, feel free to reopen your PR to fix this issue!

**Comment by EthanThatOneKid** [comment]
Resolved by #665.
