### ISSUE TITLE
Button does not render correctly in darkmode

### ISSUE THREAD

**Issue by vudiep411** [acmcsufoss/acmcsuf.com#658]
### What happened?

 Buttons do not render properly in dark mode without javascript. The text inside the button does not display properly
![acm](https://user-images.githubusercontent.com/54611122/199172143-bff1f461-5529-4eb5-8d7b-f5fc241499ab.png)
![acmbug2](https://user-images.githubusercontent.com/54611122/199172242-af84aba1-0fd8-4e50-ac35-7100e8a12d78.png)

**Comment by jaasonw** [comment]
i've had this issue b4, seems to fix itself when i disable my adblocker for some reason

**Comment by vudiep411** [comment]
It seems to me that —amc-dark in global.css behaves differently from each device. Even when i try on microsoft edge with no ads block it would still renders incorrectly. I changed the —acm-dark into —acm-gray and it seems to work with ads block but im not sure so i submitted a PR
