### ISSUE TITLE
Toast has no border on About us page

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#664]
### What happened?

Currently:
Light Mode (w/o border)| Dark Mode (w/o border)
--- | ---
<img width="839" alt="image" src="https://user-images.githubusercontent.com/60043611/199348536-4a48f2b1-bf86-48e8-bf10-158aa4dac596.png">|<img width="827" alt="image" src="https://user-images.githubusercontent.com/60043611/199348575-0d6eb603-48b6-4657-9703-08724a2af7db.png">

Switch to:
Light Mode (w/ border) | Dark Mode (w/ border)
--- | ---
<img width="505" alt="image" src="https://user-images.githubusercontent.com/60043611/199348975-53e97c39-d4ba-42f2-a2ed-b299e7aa795e.png">|<img width="515" alt="image" src="https://user-images.githubusercontent.com/60043611/199349024-c96ae4ba-1817-40a4-9aa9-53b6817d4056.png">

**Comment by anhduy1202** [comment]
im guilty of this 💀

**Comment by boushrabettir** [comment]
dibs on this

**Comment by k4rni** [comment]
No worries @anhduy1202! It's good you mention that so we can actually refer the PR that you created https://github.com/EthanThatOneKid/acmcsuf.com/pull/629#pullrequestreview-1152378577
