### ISSUE TITLE
Shortlinks: Proposal for convenient development shortlinks

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#678]
### Proposal

- **Goal**: Add new shortlinks with the theme of convenient acmcsuf.com development.
- **Important reminder**: Shortlinks must never begin with a path that matches an existing page on the website (ex: `/about` is already taken).
- **Convenience**: This allows acmcsuf.com contributors to mindlessly type <kbd>acmcsuf.com</kbd> followed up by the shortest possible path to where they want to go. This is more convenient than looking for the specific link elsewhere.

#### Proposed additions

```json
{
  "/blog/new": "/github/discussions/new?category=Newsletter",
  "/pull": "/github/pull"
}
```

Feel free to suggest more shortlinks in the comments below.

**Comment by k4rni** [comment]
Update https://acmcsuf.com/gfi to:

```json
{
  "/gfi": "/issues?q=is%3Aopen+is%3Aissue+label%3Abulbasaur%2Csquirtle%2Ccharmander",
  "/gfi/front": "/issues?q=is%3Aopen+is%3Aissue+label%3Asquirtle",
  "/gfi/back": "/issues?q=is%3Aopen+is%3Aissue+label%3Abulbasaur",
  "/gfi/misc": "/issues?q=is%3Aopen+is%3Aissue+label%3Acharmander"
}
```
Reference:
![image](https://user-images.githubusercontent.com/60043611/200160729-a1c7dbaa-be5a-4a3a-9736-8f058e5d90fb.png)
