### ISSUE TITLE
Icons for Google Calendar and Outlook are missing

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#683]
### What happened?

In PR #677, the icons for the Google Calendar copy link and the Outlook copy link were removed.
![image](https://user-images.githubusercontent.com/60043611/200165951-f1d8a8eb-c59c-4240-9c8b-1f23025d91d2.png)

However, these previous icons were much too complex and should be replaced with a simpler design.
![image](https://user-images.githubusercontent.com/60043611/200166069-39af1301-6ecc-4136-aeba-bac9a211d81a.png)

**Comment by nishtha53** [comment]
Can I work on this issue?

**Comment by EthanThatOneKid** [comment]
> Can I work on this issue?

For now, we are assigning certain issues to CSUF students only. Thank you for your interest!

**Comment by EthanThatOneKid** [comment]
This issue is resolved by #708.
