### ISSUE TITLE
Events: Location name escapes special characters

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#695]
### What happened?

An event is created on Google Calendar featuring a comma in the location name.

![image](https://user-images.githubusercontent.com/31261035/200652059-49182f23-17e5-4398-adab-a7e0ddbadaea.png)

Unlike what we want, the event summary is rendered using the escaped event name.

![image](https://user-images.githubusercontent.com/31261035/200653949-ab80faae-b62d-4e69-baaf-c272ef37449e.png)

### What should happen instead

We want special characters to display an unescaped location on the event summary.

Note: Unescaping should be abstracted into a helper function in `src/lib/server/events/ical.ts` since it must be applied to all event text properties (e.g. title, summary, and location).

Related: The resolution of #646 will pass event data that is unescaped by default.

**Comment by k4rni** [comment]
Fixed with #696.
