### ISSUE TITLE
Events: Broken Button Images for Copying to Clipboard

### ISSUE THREAD

**Issue by AmaJC** [acmcsufoss/acmcsuf.com#698]
### What happened?

On the events page, when expanding an event, you can see the two leftmost buttons seem to have broken images. (Copied Microsoft Outlook calendar link to clipboard!) and (Copied Google Calendar link to clipboard!) 

See screenshot below:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/12668870/200980175-80ae3614-c6fc-46fa-95d1-05d4c0510596.png">

Zoomed in on the broken images and highlighted the alt text that appears instead:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/12668870/200980447-272f8c01-2a15-4ca9-9e99-decbf5c74a1b.png">

**Comment by jaasonw** [comment]
look like this pull request that change the svgs didnt get the file names correct

https://github.com/EthanThatOneKid/acmcsuf.com/pull/677/files
![image](https://user-images.githubusercontent.com/8981287/201105660-9a6c4923-2684-4cf1-a487-5dab1a9ec39a.png)

**Comment by boushrabettir** [comment]
Can I try to fix this?
