### ISSUE TITLE
package-json hotfix fails deployment on vercel

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#710]
https://github.com/EthanThatOneKid/acmcsuf.com/pull/705 fails to deploy so i temporarily reverted it with https://github.com/EthanThatOneKid/acmcsuf.com/pull/709

**Comment by charliettaylor** [comment]
imagine opening an issue and not resolving it with your PR, and merging without checking the logs for why the hotfix failed

**Comment by jaasonw** [comment]
valid point but shouldn't the logs have been checked when the original pr failed the deployment in the first place?
![image](https://user-images.githubusercontent.com/8981287/201513638-c0c0bdf7-4f28-48df-abc3-de9096ec0561.png)

**Comment by k4rni** [comment]
Is this issue fixed with #709? If so, feel free to close this issue _with a comment_.

However, I believe Ethan is working on a migration currently as shown in #697.

**Comment by jaasonw** [comment]
it's "fixed" in the sense that it deployed but it's supposed to be a temporary fix until we can get it to deploy. this issue is supposed to be a reminder that it needs to be fixed

**Comment by jaasonw** [comment]
fixed w migration
