### ISSUE TITLE
acm team quiz visual errors

### ISSUE THREAD

**Issue by AlanCortez1337** [acmcsufoss/acmcsuf.com#734]
### What happened?

Was just taking a nice walk up Mt. Everest when it struck me that I had not done the ACM Team Quiz in the last 4 minutes! So I went to acmcsuf.com/quiz and noticed there have been some additions made to the quiz. This honestly just warmed me to the core which was honestly needed since I am on Mt. Everest and rapidly becoming an icecube. However, it must have been silly hour because i found some quirky visual errors the quiz!!!! 😱😱😱😱😱😱

There is an extra ">" in from of the "want to help" button
![extra symbol](https://user-images.githubusercontent.com/78040578/206308991-9d7ce32b-6375-4386-8087-b24c5f18bb49.PNG)

The right arrow is a left arrow throughout the quiz
![silly little error with arrow](https://user-images.githubusercontent.com/78040578/206308994-3105fa36-330e-43ed-9e8e-bde10d28e580.PNG)

**Comment by nghuyhoang0204** [comment]
I want to try out more about your project so can i make a PR to this issue . Thank you if you agree😄

**Comment by EthanThatOneKid** [comment]
> I want to try out more about your project so can i make a PR to this issue . Thank you if you agree😄

Sounds good to me, @nghuyhoang0204! Thanks for showing interest.
