### ISSUE TITLE
Blog: Hover and visit effect on links

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#745]
### What's your idea?

Links inside of blog posts do not give off any effect when hovered over or visited.

### Boring screenshot

<img width="212" alt="image" src="https://user-images.githubusercontent.com/31261035/209713780-9703c5c3-383b-40f5-9231-1996d8232982.png">

One link is being hovered over and one link has been visited, but you cannot tell. Hence the issue.

### References

- <https://developer.mozilla.org/en-US/docs/Web/CSS/:hover#examples>
- <https://developer.mozilla.org/en-US/docs/Web/CSS/:visited#examples>

**Comment by nghuyhoang0204** [comment]
Hello there , i wonder if i can try out for this issue and make a PR as soon as possible 
Will appreciate if the answer is yes 😄

**Comment by EthanThatOneKid** [comment]
> Hello there , i wonder if i can try out for this issue and make a PR as soon as possible Will appreciate if the answer is yes 😄

The answer is yes; go for it! @nghuyhoang0204, [here](https://github.com/EthanThatOneKid/acmcsuf.com/blob/0fc1487085506a43ea06abcc59080838693e51d8/src/routes/(site)/blog/%5Bid%5D/blog-body.svelte#L37) is where we style the blog post HTML. Please use the `var(--acm-blue)` color.

**Comment by nghuyhoang0204** [comment]
Sure , thanks for your reply and your guidance 😄

**Comment by k4rni** [comment]
Resolved by #771.
