### ISSUE TITLE
1st: Top text unselectable

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#751]
### What happened?

The confetti animation seems to cover the text at the top of the page such that the text is currently unselectable. This makes links to more information unreachable.

**Comment by EthanThatOneKid** [comment]
To be clear, the page this issue is referring to is <https://acmcsuf.com/1st>.

**Comment by JustinStitt** [comment]
Add `pointer-events: none;` to `.confetti-wrapper`. 👍🏼

**Comment by JustinStitt** [comment]
Fixed by #867.
