### ISSUE TITLE
404 page: Title is behind the navbar

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#759]
### What happened?

The CSS of the 404 error page is off and adjusts so that you are unable to see the title as it is put behind the navbar. This issue only occurs on certain devices with a different screen size. A smaller screen size will face this issue.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/31261035/213950636-3bf8c01a-637f-40a6-a19d-7fbbff48b631.png">

**Comment by nghuyhoang0204** [comment]
Hey, it's me again xD. Because I have to do some PRs for my courses at university so that after did some contributes for your project, I think I could help more to fix some bugs that i found i can do. So I want to PR this issue. Thanks for advance and let me know if i can do it 😃

**Comment by EthanThatOneKid** [comment]
> So I want to PR this issue. Thanks for advance and let me know if i can do it 😃

Hello again, @nghuyhoang0204. Thanks for your prior contributions. That would be awesome if you could please take a look at this issue!

> I think I could help more to fix some bugs that i found i can do.

If you find any new bugs, feel free to report them using our issue template: <https://acmcsuf.com/bug>. :bug:
