### ISSUE TITLE
Events: Modernize sample events for 2023

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#798]
Update the sample events to include sample events hosted by each of the 2023 branches.

Current sample events: <https://github.com/EthanThatOneKid/acmcsuf.com/blob/91af955b537333b1ab7a571493fbd33f21e52a4d/src/lib/server/events/data/sample-events.json>

**Comment by k4rni** [comment]
Duplicate of #799.
