### ISSUE TITLE
package.json: Update test script

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#803]
### What happened?

The test script currently combines the Vitest tests and the Playwright into one script. This is inconvenient since I find myself <kbd>Ctrl</kbd>+<kbd>c</kbd>'ing right after the Vitest tests finish running to avoid running the Playwright tests.

### Suggestion

Separate the `test` script into two new scripts. This requires editing the [Website Check workflow](https://github.com/EthanThatOneKid/acmcsuf.com/actions/workflows/check_website.yaml), though.

**Comment by jaasonw** [comment]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/8981287/224457581-346244c0-fde2-43ab-b9e5-087fdbb311a0.png">

while you're at it can you update the github action : )

**Comment by k4rni** [comment]
Resolved with #805.
