### ISSUE TITLE
Website Check: Update deprecated code

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#804]
> <img width="1380" alt="image" src="https://user-images.githubusercontent.com/8981287/224457581-346244c0-fde2-43ab-b9e5-087fdbb311a0.png">
> while you're at it can you update the github action : )

_Originally posted by @jaasonw in https://github.com/EthanThatOneKid/acmcsuf.com/issues/803#issuecomment-1464747874_

**Comment by jaasonw** [comment]
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/8981287/224459220-dd24d2bb-9168-43b3-aecb-ac81a0f7c67a.png">
on gitcored too thanks smile

**Comment by jaasonw** [comment]
@karnikaavelumani https://github.com/EthanThatOneKid/acmcsuf.com/actions/runs/4389986907

**Comment by k4rni** [comment]
Resolved with #805.

**Comment by k4rni** [comment]
> <img alt="image" width="1358" src="https://user-images.githubusercontent.com/8981287/224459220-dd24d2bb-9168-43b3-aecb-ac81a0f7c67a.png">
> 
> on gitcored too thanks smile
