### ISSUE TITLE
Blog: Shows author tag instead of full name

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#808]
### What happened?

See title. 

Related: #488.

**Comment by k4rni** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/60043611/236947940-fe7d650e-5eb1-4038-835d-3445a1516f00.png">

The GraphQL API does not allow you to fetch a user's full name. In this instance, the "actor" represents a user with the ability to retrieve the avatar, login, and url.

**Comment by k4rni** [comment]
Since the ID is not provided the actor resource, it is very difficult to move further with this feature.
