### ISSUE TITLE
Inconsistent variable name `Url`

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#817]
### What happened?

It can be tricky deciding which way to capitalize a variable name. Let's make it not so tricky by deciding that from this point, all camel case variable names containing acronyms should always be fully capitalized unless it is the first segment of the camel case variable name.

For example:

**OK** | **NOT OK**
---|---
`getURL` | `getUrl`
`urlFrom` | `UrlFrom`

Related:
- [`fa28791` (Comment)](https://github.com/EthanThatOneKid/acmcsuf.com/commit/fa28791369259bc370e866210a3aef1061a7030b#r105160756)

**Comment by EthanThatOneKid** [comment]
Note: `JsonUrl` should be renamed to something more accurate, such as `PageDataURL`.

**Comment by Louiza02** [comment]
Hi, 
I would be happy to fix this

**Comment by EthanThatOneKid** [comment]
> Hi,
> I would be happy to fix this

Hi @Louiza02! Feel free to fork this repository and fix this issue.

**Comment by Louiza02** [comment]
Hi @EthanThatOneKid,
If I understand well the issue, I think it has already been resolved at commit 6adad2a
Please tell me if I'm wrong
Thank you

**Comment by EthanThatOneKid** [comment]
> Hi @EthanThatOneKid, If I understand well the issue, I think it has already been resolved at commit [6adad2a](https://github.com/EthanThatOneKid/acmcsuf.com/commit/6adad2add8deba3e2737aabd0b380113c52ebf5c) Please tell me if I'm wrong Thank you

@Louiza02 thank you for looking into this issue! The issue is still open because there are some inconsistent instances of `Url` in the source code. Here are a few instances:

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/9f64ddcb19cd38e67c553c1d444d6e135857e484/src/lib/public/blog/urls.ts#L3>
<https://github.com/EthanThatOneKid/acmcsuf.com/blob/9f64ddcb19cd38e67c553c1d444d6e135857e484/src/lib/public/blog/urls.ts#L8>
<https://github.com/EthanThatOneKid/acmcsuf.com/blob/9f64ddcb19cd38e67c553c1d444d6e135857e484/src/lib/public/blog/urls.ts#L13>

**Comment by EthanThatOneKid** [comment]
Resolved by #866.
