### ISSUE TITLE
Events: Event component minor regressions

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#832]
### What happened?

- Event preview elements are always highlighted by default when they should only be highlighted when hovered over or opened.
- Spacing between the action buttons and the event description text is small.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/31261035/230683514-3ed5e3f9-bc2f-478c-9fa7-d03966ee83f2.png">

**Comment by JustinStitt** [comment]
How can I add dummy events in dev?
