### ISSUE TITLE
Homepage logo padding

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#840]
> I apologize I meant the logos. The reason for the overflow was because I updated the assets with no padding. Before when there was padding, the logos looked a bit smaller.
> 
> You might have to change the width now or just add padding to the img tag.

>Honestly, out of scope of my PR. Create an issue (or revive an old issue) and create a new PR after this one is merged.

>It's meaningless to discuss how many pixels the logos should be smaller by then I go and do it and update my PR only to be off by a few pixels of what is desired.

>I was mainly concerned with text alignment and tall display styles.

_Originally posted by @JustinStitt in https://github.com/EthanThatOneKid/acmcsuf.com/pull/839#issuecomment-1522878225_

Add padding or decrease the width of the logos on the home page

**Comment by JustinStitt** [comment]
Here's a quick screen grab of the current design on an iPhone 12. What __exactly__ do you think should change @karnikaavelumani?

![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/24460581/38ed74c9-88f7-4369-9be0-eb5dbf06c359)


Should we **increase** the whitespace around the team name's... something like **this**?
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/24460581/a12c17e5-eeab-4806-a638-2fbce38cb38f)

**Comment by EvanCPSC** [comment]
Those images are deprecated from the site. 👍
