### ISSUE TITLE
Favicon is old

### ISSUE THREAD

**Issue by jiink** [acmcsufoss/acmcsuf.com#843]
### What happened?

![image](https://user-images.githubusercontent.com/35513545/235008142-0449a9d9-3dbd-4af8-94e9-05a40e120dc8.png)
When going anywhere in acmcsuf.com, the logo in the favicon is the old outdated logo and not the new redesigned logo. Since the favicon and the logo on the site are near eachother, this becomes quite noticable.

**Comment by Nanak360** [comment]
I can take it up and start working on it. Seems pretty straightforward to me.

**Comment by EthanThatOneKid** [comment]
> I can take it up and start working on it. Seems pretty straightforward to me.

Thank you for your interest in this issue, @Nanak360. Our latest logo should already be inside the repository. As for generating Favicon assets, I recommend using a tool such as <https://favicon.io/favicon-converter/>.

**Comment by Nanak360** [comment]
@EthanThatOneKid I have raised a pr
Please have a look
Let me know if any changes are required

**Comment by jiink** [comment]
Great!
