### ISSUE TITLE
Board: Unnecessary legacy pictures

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#877]
### What happened?

In <https://github.com/EthanThatOneKid/acmcsuf.com/blob/f6a51383763dd6608897db49d9d740fca14a8600/src/lib/public/board/data/officers.json>, instances of “legacyPicture”: “placeholder.webp” are not required since the absence of “picture” and “legacyPicture” results in the automatic usage of “placeholder.webp”. 

Follow-up to #870.

**Comment by k4rni** [comment]
Fixed in #906.
