### ISSUE TITLE
Update Google Form implementation

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#88]
Convert the current Google Form implementation from an iframe back to a form element that submits directly to the Google Form's endpoint.

Resources: <https://github.com/jsdevel/google-form>

**Comment by diamondburned** [comment]
This unfortunately isn't viable anymore due to CORS, but since we already have a Vercel server, can we setup a lambda function to forward the form? 

cc @EthanThatOneKid

**Comment by EthanThatOneKid** [comment]
Status on this issue: We are waiting on admin to gain access to a Mailchimp account in order to properly implement the HTML form. Once the account is back in our possession, we can use the account to create an automatic email alert service for admins to receive emails from responses on the contact page.

**Comment by EthanThatOneKid** [comment]
Since the `/connect` page has been removed in [v2.0](https://github.com/EthanThatOneKid/acmcsuf.com/milestone/1), we no longer need to maintain the Google form.
