### ISSUE TITLE
Board: Mobile Flip Interaction shows picture overlayed on socials

### ISSUE THREAD

**Issue by caretcakejake** [acmcsufoss/acmcsuf.com#881]
### What happened?

If you flip some of the members in marketing on mobile you get a really weird interaction where the picture is overrated on peoples socials. 

https://github.com/EthanThatOneKid/acmcsuf.com/assets/40745961/a77bf199-8c7f-4b50-ba18-dacf0d4093af

**Comment by caretcakejake** [comment]
Just tested on Chrome and Safari on another device and it works I suspect it's a caching issue
Edit: Nvm the cache isn't the issue

**Comment by caretcakejake** [comment]
Affected board badges:
- Ashley Kuewa
- Brian Milian
- Angela Queano
- Joann Sum
- Nicholas Girmes
- David Solano
- Cyril Youssef
- Tanisa Naik
- Oscar Cisneros
- Joe Lee
- Vanessa Roque
- Alexander Zaveleta
- Jacob Carlson
- Joseph Nasr

**Comment by jaasonw** [comment]
happens on my safari too

**Comment by jaasonw** [comment]
https://github.com/EthanThatOneKid/acmcsuf.com/assets/8981287/812b9bb5-b4dc-4da7-93ae-4200fea11dcd

**Comment by EthanThatOneKid** [comment]
I found a quick fix: just use Chrome /j

**Comment by diamondburned** [comment]
> Just tested on Chrome and Safari on another device

Clarification: this should only happen on Chrome for iOS, specifically because all browsers on iOS are forced to use Safari.
