### ISSUE TITLE
Remove playwright tests

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#920]
### What happened?

The playwright tests currently do not work (Reference: https://github.com/EthanThatOneKid/acmcsuf.com/pull/884#pullrequestreview-1555545355), so they should be removed for the time being until properly fixed.

**Comment by EthanThatOneKid** [comment]
Related: https://github.com/EthanThatOneKid/acmcsuf.com/pull/884#pullrequestreview-1555545355

**Comment by EthanThatOneKid** [comment]
Last used Playwright config: <https://github.com/EthanThatOneKid/acmcsuf.com/blob/84efe8e4c64da9396c815c0484be39917d97009a/playwright.config.ts>.
