### ISSUE TITLE
Create Testimonials component

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#926]
### What's your idea?

Redesign the testimonials component in acmcsuf.com following the provided image:

Light mode desktop | Light mode mobile | Dark mode desktop | Dark mode mobile
---|---|---|---
![light-desktop-testimonies](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/0ba13369-6602-400a-aa54-fe56333753f6) | ![light-mobile-testimonies](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/8df51c3e-e041-44f5-b09a-960652cb1def) | ![dark-desktop-testimonies](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/bf23c364-d5fb-4ea8-8d68-b1daa7f122f0)| ![dark-mobile-testimonies](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/babb630d-7679-41ef-bc50-e04eb68355a8)

**Comment by EthanThatOneKid** [comment]
### Prior art

Original Nodebuds page: #58 ([demo](https://acm-csuf-site-git-fork-bjwarfield-main-ethanthatonekid.vercel.app/nodebuds))

![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/31261035/57eb5f44-1d5a-49fe-a311-dd42743d41e3)
