### ISSUE TITLE
About page hero component

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#940]
### What's your idea?

Redesign the hero component in acmcsuf.com/about following the provided image:

Light mode desktop | Light mode mobile | Dark mode desktop | Dark mode mobile
---|---|---|---
![hero](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/e78f8c42-639c-42d6-bcbd-d3af2345ecf2) | ![light-mobile-hero](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/0feefb3f-e45c-412c-b8b5-f26e575a71ce) | ![hero-dark](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/069d4667-7059-4f78-bebf-b1e242f0986c) | ![dark-mobile-hero](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/306ab50c-796e-4242-af7f-0082609f0ff5)

**Comment by juyeongk365** [comment]
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/111930167/cc481ddd-8299-49e3-905b-2f04ac5632ce)

From what I understood, you want me to redesign this **acmcsuf.com/about** page like the image you have provided, right? If so, where can I get the new image? I looked at /png and did not find any image that looked identical with the provided image.
