### ISSUE TITLE
About page special events component

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#944]
### What's your idea?

Redesign the special events component in acmcsuf.com/about following the provided image:

Light mode desktop | Light mode mobile | Dark mode desktop | Dark mode mobile
---|---|---|---
![light-desktop-spec-events](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/b396d319-f434-401b-8357-08d30f5c5167) | ![light-mobile-spec-events](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/92c8b16e-6bcf-45c3-8090-54fb962c6d6f) | ![dark-desktop-spec-events](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/51a82b49-558f-4538-9eaf-bc902cae452c) | ![dark-mobile-spec-events](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/dc38d22f-648a-4dd3-8be0-5168eb129f4c)

**Comment by Charoutyun** [comment]
Id like to work on this.

**Comment by k4rni** [comment]
Special events team has been added to the `acmcsuf.com/teams` page.
