### ISSUE TITLE
Add a margin on the description component on acmcsuf.com/6

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#981]
### What happened?

To prevent the text from appearing directly on the edge of the screen, a margin or padding should be added to the text of the description component on the acmcsuf.com/6 page. This issue occurs on desktop/tablet mode and not necessarily on mobile mode so the changes applied should not affect mobile mode significantly.

![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/1224a8e3-6ad1-4fe9-84bd-cbd35d4f5553)

**Comment by EvanCPSC** [comment]
hi im stealing this

**Comment by EvanCPSC** [comment]
https://github.com/EthanThatOneKid/acmcsuf.com/pull/988
