### ISSUE TITLE
General logo animation is blurry

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmcsuf.com#986]
### What happened?

The animation on the ACM General logo is slightly blurry. Can someone create a new animation that fits more to theme? The water animation was in relation to the previous mascot, Frank the Shark.

![general](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/9dffa1cd-b2b6-4030-84ac-d11d0a78baec)

I am editing... :godmode:

**Comment by EthanThatOneKid** [comment]
Capybaras can swim too 🏊

**Comment by EvanCPSC** [comment]
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/142952307/8f889bd8-137e-4002-905e-14ece8f9fd57)

**Comment by EvanCPSC** [comment]
This was fixed with a new animation.
